### ISSUE TITLE
Downloading by disabling ask where to save

### ISSUE THREAD

**Issue by esinanturan** [up209d/ResourcesSaverExt#1]
I get issue when I try to download resources by closing chromes choose where to save feature. It doesnt downloads all the files and just stops downloading what should we do about that

**Comment by up209d** [comment]
Normally, I disabled the Saving dialogs for all downloads, so if it is showed up, that means there is a problem with the saving path of assets. The extension mimics the path of assets to save down to resource folder, however some paths are not valid by chrome downloads function, for exp: containing violated special characters ~#[]... I tried to cover all the cases, but it seem there are still some left as a result you are seeing. I shall work it out more and update it soon. Thank you for using my ext.

**Comment by esinanturan** [comment]
I dont mean saving dialogs , I mean if I close ask where to save feature I cant download after first download or something. But If I open the feature it works but at this time I have to accept like thousands of ask where to save.

**Comment by up209d** [comment]
Oops, I think there might be a conflict with that feature since i just make this ext work with vanilla Chrome with default configuration. And also you might be using some ext which also make effect to chrome.download environment. Normally i disabled the download bar & notification when the ext start to download and turn it on again when all download process is done, but during that process if some ext enable the configuration automatically, that might cause your problem. Maybe you can try it on Chrome Canary or Chromium without any ext installed.
