### ISSUE TITLE
Cannot untick option to save in a zip file

### ISSUE THREAD

**Issue by unleashed7** [up209d/ResourcesSaverExt#38]
I am not sure if this is intended (as the checkbox is grayed out), but assuming it's not since it says "Recommended".

Or is it not possible to download just certain resources? Since I wouldn't want to download 1000+ files repeatedly.

**Comment by Gregory-Ledray** [comment]
If you didn't save in a Zip file each file would be individually downloaded to your computer. So if you had a 1,000 file website, you would download 1,000 files into your Downloads folder separately.

I do not know if there is a way to use this extension to avoid re-downloading resources which are common between different pages or to just download certain resources. If you want to download a specific image or video you can usually Right click it in Chrome and save it (for images) and there are similar ways to download other resources.

**Comment by unleashed7** [comment]
I see.. I guess I was just confused, why would there be a tickbox for this, especially mixed between other, actually working options.

**Comment by duc-duong-energetiq** [comment]
That option is running on the old setup which is re-download and saves each individual file by chrome itself, it is not stable and can lead to not clearing the download history properly, so I just disabled that for safety. You can load the local extension by cloning this repo and change the code inside otherwise can hack the tick active and you can tick it on/off.
