### ISSUE TITLE
Merge resource files when saving them

### ISSUE THREAD

**Issue by sic-sic** [up209d/ResourcesSaverExt#5]
It would be nice to have options that permits users to skip files which already exist in destination folder or to overwrite existing ones.

**Comment by up209d** [comment]
Hi brother, thanks for your idea. However, that is not quite possible since chrome doesn't allow extensions to overwrite file. Also, there are some cases with the same filename but different query string. These will return different content for example: getPost.php?post=123 | getPost.php?post=456, so sometimes it seems not to be right to skip the existed files instead of greedily getting them all. I actually did a basic excluding if the url with full query is not unique.
